learning/demo/demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("learning.urls", namespace="learning")),
    path('markdownx/', include('markdownx.urls'))
]

learning/urls.py
#
# Copyright (C) 2019 Guillaume Bernard <guillaume.bernard@koala-lms.org>
#
# This file is part of Koala LMS (Learning Management system)

# Koala LMS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# We make an extensive use of the Django framework, https://www.djangoproject.com/
#

from django.urls import path, include

import learning.views.activity as activity_views
import learning.views.course as course_views
import learning.views.resource as resource_views
from learning.views.views import WelcomePageView

app_name = 'learning'  # Application namespace

###############
# Course ULRs #
###############

course_details_urlpatterns = [
    # The course itself
    path('', course_views.CourseDetailView.as_view(), name='course/detail'),

    # Access courses similar to the current one
    path('similar/', course_views.CourseDetailSimilarView.as_view(), name="course/detail/similar"),

    # Registration on a course, for a student
    path('register', course_views.CourseRegisterView.as_view(), name="course/detail/register"),
    path('unregister', course_views.CourseUnregisterView.as_view(), name="course/detail/unregister"),

    # Activities: view (as student and as teacher), add, unlink and delete from a course
    path('activities', course_views.CourseDetailActivitiesView.as_view(), name="course/detail/activities"),
    path(
        'activity/<slug:activity_slug>/',
        course_views.CourseDetailActivitiesView.as_view(),
        name="course/detail/activity"
    ),
    path(
        'activity/<slug:activity_slug>/resource/<slug:resource_slug>',
        course_views.CourseDetailActivityResourceView.as_view(),
        name="course/detail/activities/resource"
    ),
    path('activity/up', course_views.activity_on_course_up_view, name="course/detail/activity/up"),
    path('activity/add', course_views.ActivityCreateOnCourseView.as_view(), name="course/detail/activity/add"),
    path('activity/attach', course_views.ActivityAttachOnCourseView.as_view(), name="course/detail/activity/attach"),
    path('activity/unlink', course_views.activity_on_course_unlink_view, name="course/detail/activity/unlink"),
    path('activity/delete', course_views.activity_on_course_delete_view, name="course/detail/activity/delete"),

    # Collaborators: view, add and delete from a course
    path('collaborators', course_views.CourseDetailCollaboratorsView.as_view(), name="course/detail/collaborators"),
    path('collaborator/add', course_views.CourseDetailCollaboratorsAddView.as_view(), name="course/detail/collaborator/add"),
    path('collaborator/update', course_views.CourseDetailCollaboratorsChangeView.as_view(), name="course/detail/collaborator/change"),
    path('collaborator/delete', course_views.CourseDetailCollaboratorsDeleteView.as_view(), name="course/detail/collaborator/delete"),

    # Students: view, add and delete from a course
    path('students/', course_views.CourseDetailStudentsView.as_view(), name="course/detail/students"),
    path('students/add', course_views.CourseDetailStudentsAddView.as_view(), name="course/detail/students/add"),
    path('students/delete', course_views.CourseDetailStudentsDeleteView.as_view(), name="course/detail/students/delete"),
]

course_urlpatterns = [
    path('study', course_views.CourseAsStudentListView.as_view(), name='course/my'),
    path('teach/', course_views.CourseAsTeacherListView.as_view(), name="course/teaching"),
    path('search/', course_views.CourseSearchView.as_view(), name="course/search"),

    # Course view, add, update and delete views
    path('add/', course_views.CourseCreateView.as_view(), name='course/add'),
    path('update/<slug:slug>/', course_views.CourseUpdateView.as_view(), name='course/update'),
    path('delete/<slug:slug>/', course_views.CourseDeleteView.as_view(), name='course/delete'),
    path('detail/<slug:slug>/', include(course_details_urlpatterns)),
]

#################
# Activity ULRs #
#################

activity_details_urlpatterns = [
    # The activity itself
    path('', activity_views.ActivityDetailView.as_view(), name='activity/detail'),

    # Add a new resource on this activity
    path('resource/add', activity_views.ActivityCreateResourceView.as_view(), name="activity/detail/resource/add"),
    path('resource/attach', activity_views.ResourceAttachOnActivityView.as_view(), name="activity/detail/resource/attach"),
    path('resource/unlink', activity_views.ResourceUnlinkOnActivityView.as_view(), name="activity/detail/resource/unlink"),
    path('resource/detail/<slug:resource_slug>', activity_views.ResourceOnActivityDetailView.as_view(), name="activity/resource/detail"),

    # By which courses the activity is used
    path('usage/', activity_views.ActivityDetailUsageView.as_view(), name="activity/detail/usage"),

    # Activities similar to the current one
    path('similar/', activity_views.ActivityDetailSimilarView.as_view(), name="activity/detail/similar"),
]

activity_urlpatterns = [
    path('', activity_views.ActivityListView.as_view(), name="activity/my"),

    # Activity view, add, update and delete views
    path('add/', activity_views.ActivityCreateView.as_view(), name='activity/add'),
    path('delete/<slug:slug>/', activity_views.ActivityDeleteView.as_view(), name='activity/delete'),
    path('update/<slug:slug>/', activity_views.ActivityUpdateView.as_view(), name='activity/update'),
    path('detail/<slug:slug>/', include(activity_details_urlpatterns)),
]

#################
# Resource ULRs #
#################

resource_details_urlpatterns = [
    # The resource itself
    path('', resource_views.ResourceDetailView.as_view(), name="resource/detail"),

    # By which activities the activity is used
    path('usage/', resource_views.ResourceDetailUsageView.as_view(), name="resource/detail/usage"),

    # Resources similar to the current one
    path('similar/', resource_views.ResourceDetailSimilarView.as_view(), name="resource/detail/similar"),
]

resource_urlpatterns = [
    path('', resource_views.ResourceListView.as_view(), name="resource/my"),

    # Resource view, add, update and delete views
    path('add/', resource_views.ResourceCreateView.as_view(), name='resource/add'),

    path('delete/<slug:slug>/', resource_views.ResourceDeleteView.as_view(), name='resource/delete'),
    path('update/<slug:slug>/', resource_views.ResourceUpdateView.as_view(), name='resource/update'),
    path('detail/<slug:slug>/', include(resource_details_urlpatterns)),
]

####################
# Application URLs #
####################
urlpatterns = [
    path('', WelcomePageView.as_view(), name='index'),
    path('course/', include(course_urlpatterns)),
    path('activity/', include(activity_urlpatterns)),
    path('resource/', include(resource_urlpatterns))
]

learning/models.py
#
# Copyright (C) 2019 Guillaume Bernard <guillaume.bernard@koala-lms.org>
#
# This file is part of Koala LMS (Learning Management system)

# Koala LMS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# We make an extensive use of the Django framework, https://www.djangoproject.com/
#
import abc
import itertools
import os
from enum import Enum

from django.conf import global_settings, settings
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Max, QuerySet, Q
from django.template.defaultfilters import filesizeformat
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from django.utils.translation import pgettext_lazy
from taggit.managers import TaggableManager

import learning.exc
from learning import logger
from learning.permissions import ObjectPermissionManagerMixin


def get_max_upload_size():
    try:
        upload_size = settings.LEARNING_UPLOAD_SIZE
    except AttributeError:
        upload_size = 2**20  # 1Mio
    return upload_size


def get_translated_languages():
    """
    Get the list of languages supported by Django, translated in the current locale.

    .. note:: Languages are wrapped around the “noop_gettext” function which does not translate them at runtime.

    :return: a list of tuples containing the language code and the translated version of the language name
    :rtype: list of tuples
    """
    languages = []
    for code, language in global_settings.LANGUAGES:
        languages.append((code, _(language)))
    return languages


def generate_slug_for_model(model, instance):
    """
    Generate a slug value for a specific instance. It is made to avoid dupliacates, as slugs are unique. \
    In case of two instance having the same slug_value, hence the same slug, a counter is added at the end \
    of the slug.

    :param model: the concrete model of the instance
    :type model: class
    :param instance: an instance of a ObjectWithSlugMixin
    :type instance: ObjectWithSlugMixin
    :return: a slug made from the instance
    :rtype: str
    """
    max_length = model._meta.get_field('slug').max_length
    slug = instance.slug = original_slug = slugify(instance.slug_generator())[:max_length]

    # If necessary, add an index (1, 2, etc.) to the slug field if another Resource exists
    # with the same slug
    for counter in itertools.count(1):
        # noinspection PyUnresolvedReferences
        if not model.objects.filter(slug=slug).exclude(pk=instance.id).exists():
            break  # The slug is not used by another resource
        slug = "{slug}-{counter}".format(slug=original_slug[:max_length - len(str(counter)) - 1], counter=counter)
    return slug


class OrderedEnum(Enum):
    """
    Special enumeration which can has ordered elements. Each literal has a weight which is used to compare with others.

    .. warning:: Literals are tuples with a value and a weight, like:
        A = ('A', 0)
        B = ('B', 1
    """

    # pylint: disable=unused-argument
    # noinspection PyUnusedLocal
    def __init__(self, token, weight):
        self.__weight = weight

    @property
    def weight(self):
        return self.__weight

    @property
    def value(self):
        return super().value[0]

    def __eq__(self, other):
        return self.weight == other.weight

    def __lt__(self, other):
        return self.weight < other.weight

    def __gt__(self, other):
        return self.weight > other.weight

    def __le__(self, other):
        return self.weight <= other.weight

    def __ge__(self, other):
        return self.weight >= other.weight


class Licences(OrderedEnum):
    CC_0 = (_("Creative Commons 0 (Public domain)"), 0)
    CC_BY = (_("Creative Commons Attribution"), 1)
    CC_BY_SA = (_("Creative Commons Attribution, Share Alike"), 2)
    CC_BY_NC = (_("Creative Commons Attribution, Non Commercial"), 3)
    CC_BY_NC_SA = (_("Creative Commons Attribution, Non Commercial, Share Alike"), 4)
    CC_BY_ND = (_("Creative Commons Attribution, No Derivatives"), 5)
    CC_BY_NC_ND = (_("Creative Commons Attribution, No Commercial, No Derivatives"), 6)
    NA = (_("Not appropriate"), 7)
    ALL_RIGHTS_RESERVED = (_("All rights reserved"), 8)


class Duration(OrderedEnum):
    FIVE_OR_LESS = (_("Less than 5 minutes"), 0)
    TEN_OR_LESS = (_("Less than 10 minutes"), 0)
    FIFTEEN_OR_LESS = (_("Less than 15 minutes"), 1)
    TWENTY_OR_LESS = (_("Less than 20 minutes"), 1)
    TWENTY_FIVE_OR_LESS = (_("Less than 25 minutes"), 2)
    THIRTY_OR_MORE = (_("30 minutes or more"), 2)
    NOT_SPECIFIED = (_("Not specified"), 3)


class ResourceAccess(OrderedEnum):
    PUBLIC = (_("Public"), 0)
    EXISTING_ACTIVITIES = (_("Only in activities"), 1)
    PRIVATE = (_("Private"), 2)


class ResourceReuse(OrderedEnum):
    NO_RESTRICTION = (_("Reusable"), 0)
    ONLY_AUTHOR = (_("Author only"), 1)
    NON_REUSABLE = (_("Non reusable"), 2)


class ResourceType(Enum):
    FILE = (_("File"), "fa-file-alt")
    VIDEO = (_("Video"), "fa-video")
    AUDIO = (_("Audio"), "fa-broadcast-tower")

    # noinspection PyUnusedLocal
    # pylint: disable=unused-argument
    def __init__(self, i18n_str, fa_icon):
        self.__icon = fa_icon

    @property
    def icon(self):  # pragma: no cover
        return self.__icon

    @property
    def value(self):
        return super().value[0]


class ObjectWithSlugMixin:
    """
    An interface providing a property used to generate the object slug field
    """

    @abc.abstractmethod
    def slug_generator(self):
        raise NotImplementedError()


class Resource(ObjectPermissionManagerMixin, ObjectWithSlugMixin, models.Model):
    name = models.CharField(
        max_length=255,
        verbose_name=_("Name")
    )
    description = models.TextField(
        verbose_name=_("Description")
    )
    language = models.CharField(
        max_length=20,
        choices=get_translated_languages(),
        verbose_name=_("Language")
    )
    type = models.CharField(
        max_length=10,
        choices=[(rtype.name, rtype.value) for rtype in ResourceType],
        verbose_name=_("Type")
    )
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name="resources",
        verbose_name=_("Author")
    )
    duration = models.CharField(
        max_length=30,
        choices=[(duration.name, duration.value) for duration in Duration],
        default=Duration.NOT_SPECIFIED.name,
        verbose_name=_("Duration")
    )
    licence = models.CharField(
        max_length=20,
        choices=[(licence.name, licence.value) for licence in Licences],
        default=Licences.CC_BY.name,
        verbose_name=_("Licence")
    )
    access = models.CharField(
        max_length=20,
        choices=[(access.name, access.value) for access in ResourceAccess],
        default=ResourceAccess.PUBLIC.name,
        verbose_name=_("Access")
    )
    reuse = models.CharField(
        max_length=20,
        choices=[(reuse.name, reuse.value) for reuse in ResourceReuse],
        default=ResourceReuse.ONLY_AUTHOR.name,
        verbose_name=_("Reuse")
    )
    media = models.FileField(
        blank=True, null=True,
        verbose_name=_("File")
    )
    tags = TaggableManager()

    """
    Auto-generated fields
    """
    slug = models.SlugField(unique=True)
    published = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name=_("Published the"))
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, verbose_name=_("Last updated the"))

    def slug_generator(self):
        return self.name

    def is_reusable(self, for_activity=None) -> bool:
        """
        Check if it is possible to use the resource in an activity. Resource linking depends on a few conditions, based on
        access and reuse Resource attributes.

        :raises ResourceNotReusableError: when reuse condition do not allow the Resource to be reused by any Activity
        :raises ResourceNotReusableOnlyAuthorError: when reuse condition is set to “Only author” and the Resource \
            author and the author of the activity given in parameter do not match.
        :raises RuntimeError: when reuse condition is set to “Only author” but no activity is given in parameter

        :param for_activity: in case the reuse attribute is set to “Only author”, this argument must be provided. \
            It indicates for which activity to link the resource.
        :type for_activity: Activity
        :return: True if reusing resource is possible
        :rtype: bool
        """
        reuse = ResourceReuse[self.reuse]
        # Reuse is stricter than “Only Author”, means no one has access
        if reuse > ResourceReuse.ONLY_AUTHOR:
            raise learning.exc.ResourceNotReusableError(_("Reuse conditions for this resource prevent it from being added to an activity."))
        if reuse == ResourceReuse.ONLY_AUTHOR:
            if for_activity is None:
                raise RuntimeError("If resource reuse condition is set to “Only author”, you must provide the corresponding activity.")
            if reuse == ActivityReuse.ONLY_AUTHOR and for_activity.author != self.author:
                raise learning.exc.ResourceNotReusableOnlyAuthorError(

learning/templates/learning/resource/_includes/nb_resources_badge.html
{% load i18n %}

{% with activity.resources.count as nb_resources %}
  {% if nb_resources > 0 %}
    <span id="badge-nb-course-activities" class="badge badge-pill badge-info p-2">
      {% blocktrans count counter=nb_resources %}{{ nb_resources }} resource{% plural %}{{ nb_resources }} resources{% endblocktrans %}
    </span>
  {% else %}
    <span id="badge-nb-course-activities" class="badge badge-pill badge-warning p-2">{% trans "No resource yet" %}</span>
  {% endif %}
{% endwith %}

learning/templates/learning/resource/_includes/resource_block.html
{% load i18n learning countries %}

<div id="resource-block-for-{{ resource.slug }}" class="col-lg-4 col-md-6 col-sm-6 col-12 p-2">
  <div class="card w-100 h-100">
    <div class="card-body"> <!-- Card body begins -->

      <div class="clearfix">
        {# The course identity: icon and name #}
        <h5 class="card-title float-left">
          <i class="fa {{ resource.type|get_resource_type_icon }}"></i> {{ resource.name }}
        </h5>

        {% if add %}
          {# The resource can be linked to an activity. In this case, display a button to attach it to the activity #}
          <div class="float-right">
            <form method="post" action="{% url 'learning:activity/detail/resource/attach' activity.slug %}" id="link-resource-to-activity-form">
              {% csrf_token %}
              <input name="resource" value="{{ resource.id }}" type="hidden">
              <button type="submit" class="btn btn-outline-success btn-sm"
                      data-toggle="tooltip" data-placement="top" title="{% trans "Attach the resource to the activity." %}">
                <i class="fa fa-plus"></i>
              </button>
            </form>
          </div>
        {% elif unlink %}
          {# The resource can be unlink from an activity. In this case, display a button to unlink the resource #}
          <div class="float-right">
            <form method="post" action="{% url 'learning:activity/detail/resource/unlink' activity.slug %}" id="unlink-resource-from-activity-form">
              {% csrf_token %}
              <input name="resource" value="{{ resource.id }}" type="hidden">
              <button type="submit" class="btn btn-outline-warning btn-sm"
                      data-toggle="tooltip" data-placement="top" title="{% trans "Unlink the resource from the activity." %}">
                <i class="fa fa-unlink"></i>
              </button>
            </form>
          </div>
        {% endif %}
      </div>

      <hr>

      {# The resource badges to display necessary information: access and duration #}
      <div class="clearfix">
        {# Access attribute is put on the left, this is not relevant for a student #}
        {% if not as_student %}
          <div class="float-left">
          <span class="badge p-2 badge-{{ resource.access|get_resource_access_badge_type }}"
                data-toggle="tooltip" data-placement="top" title="{{ resource.access|get_resource_access_badge_title }}">
            {{ resource.get_access_display }}
          </span>
          </div>
        {% endif %}
        {# Duration attribute is put on the right #}
        <div class="float-right">
          <span class="badge p-2 badge-{{ resource.duration|get_resource_duration_badge_type }}"
                data-toggle="tooltip" data-placement="top" title="{{ resource.duration|get_resource_duration_badge_title }}">
            {{ resource.get_duration_display }}
          </span>
        </div>
      </div>

      <hr>

      {# The resource author and main language #}
      <div class="clearfix">
        {# Author #}
        <h6 class="mb-2 text-muted float-left">
          {% blocktrans with author=resource.author %}By: {{ author }}{% endblocktrans %}
        </h6>
        {# Country #}
        <div class="float-right">
          {% get_country resource.language as country %}
          <i class="{{ country.flag_css }} align-middle"></i>
        </div>
      </div>

      {# The course tags #}
      <div class="card-text d-none d-md-block">
        {% include "learning/_includes/object_tags_line.html" with object=resource %}
      </div>

    </div> <!-- Card body ends -->

    <div class="card-footer bg-white"> <!-- Footer begins -->
      <div class="clearfix">
        {# Resource update date #}
        <p class="float-left text-muted d-none d-md-block" >
          {% blocktrans with date=resource.updated|date:'j N Y' %}Updated {{ date }}.{% endblocktrans %}
        </p>
        {% get_object_perms resource user as resource_perms %}
        {% if "view_resource" in resource_perms %}
          {% if linked_course %}
            {# In case the resource is displayed as part of a course, it is linked to it and to the corresponding activity. #}
            <a href="{% url 'learning:course/detail/activities/resource' slug=linked_course.slug activity_slug=linked_activity.slug resource_slug=resource.slug %}"
               class="card-link float-right">
          {% elif linked_activity %}
            {# If not, it may be part of an activity, so it is linked to the corresponding activity. #}
            <a href="{% url 'learning:activity/resource/detail' slug=linked_activity.slug resource_slug=resource.slug %}" class="card-link float-right">
          {% else %}
            {# Otherwise, it can be displayed as a standard resource detail page #}
            <a href="{% url 'learning:resource/detail' slug=resource.slug %}" class="card-link float-right">
          {% endif %}
        {% trans "See more" %}
        </a>
        {% else %}
          <p class="card-link float-right">{% trans "Restricted access" %}</p>
        {% endif %}
      </div>
    </div> <!-- Footer ends -->
  </div>
</div>

learning/templates/learning/resource/_includes/resource_form.html
{% load i18n learning %}

<h4>{% trans "General information" %}</h4>
<div class="form-group">
  <div class="form-row">
    <div class="col">
      {% include "learning/_includes/form_group_block.html" with field=form.name %}
    </div>
    <div class="col-auto">
      {% include "learning/_includes/form_group_block.html" with field=form.type %}
    </div>
    <div class="col-auto">
      {% include "learning/_includes/form_group_block.html" with field=form.language %}
    </div>
  </div>
  <div class="form-row">
    <div class="col">
      {% include "learning/_includes/form_group_block.html" with field=form.tags %}
    </div>
    <div class="col-auto">
      {% include "learning/_includes/form_group_block.html" with field=form.reuse %}
    </div>
    <div class="col-auto">
      {% include "learning/_includes/form_group_block.html" with field=form.access %}
    </div>
  </div>
  <div class="form-row">
    <div class="col">
      {% include "learning/_includes/form_group_block.html" with field=form.licence %}
    </div>
    <div class="col-auto">
      {% include "learning/_includes/form_group_block.html" with field=form.duration %}
    </div>
  </div>
</div>
<hr>

<h4>{% trans "Media" %}</h4>
<div class="form-group">
  <div class="form-row">
    <div class="col">
      <label for="media-file" hidden>{% trans "File" %}</label>
      <input id="id_media" name="media" type="file" class="form-control-file"/>
      <small id="media-help" class="form-text text-muted">{% blocktrans with size=media_upload_size|filesizeformat %}File size should not exceed {{ size }}.{% endblocktrans %}</small>
    </div>
    {% if form.initial.media %}
      <div class="col-auto" id="column-clear-media">
        <div data-toggle="buttons">
          <label for="media-clear_id" class="btn btn-danger">
            <i class="fa fa-trash"></i> {% trans "Clear" %}
            <input type="checkbox" class="action-checkbox align-middle" name="media-clear" id="media-clear_id">
          </label>
        </div>
      </div>
      <div class="col-auto" id="column-download-media">
        <a href="{{ form.initial.media.url }}" class="btn btn-primary" download=""
           data-toggle="tooltip" data-placement="top" title="{{ form.initial.media.name }} ({{ form.initial.media.size|filesizeformat }})">
          <i class="fa fa-download"></i> {% trans "Download the current media" %} ({{ form.initial.media.size|filesizeformat }})
        </a>
      </div>
    {% endif %}
  </div>
</div>

<hr>
<h4>{% trans "Description" %}</h4>
<div class="form-group">
  {{ form.description }}
  <span class="form-text text-muted" style="font-size: .8rem">
        {{ form.description.help_text }}
    </span>
</div>